name: macos

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source cmake

      - name: Build all
        run: |
          lrelease *.pro
          qmake -makefile
          make

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: libtimestamp
          path: |
            ./libtimestamp.dylib

  macos_arm64:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source cmake

      - name: Build all
        run: |
          lrelease *.pro
          qmake -makefile
          make
          cp libtimestamp.dylib libtimestamp.arm64.dylib

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: libtimestamp_arm64
          path: |
            ./libtimestamp.arm64.dylib
          